version: "3.6"
services:
  sockpuppet:
    depends_on: 
      - redis
    image: sockpuppet
    ports:
      - "80:80"
      - "443:443"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - net
    secrets:
      - sockpuppet-api-keys
    environment:
      SOCKPUPPET_API_KEY_PATH: /run/secrets/sockpuppet-api-keys
  redis:
    image: redis:4.0.9-alpine
    ports:
      - "6379:6379"
    volumes:
      - "/home/docker/data:/data"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - net
networks:
  net:

secrets:
  sockpuppet-api-keys:
    external: true