import pytest
from sockpuppet.model.dataset.twitter_tokenize import tokenize


@pytest.mark.parametrize("input,expected", [
    ("<3", "<heart>"),
    ("💓", "<heart>"),
    ("<3 ♥", "<heart> <heart>"),
    ("♥♥", "<heart> <heart>"),
    ("@iconography", "<user>"),
    ("@NASA", "<user>"),
    ("@", "@"),
    ("#EXCELLENT", "<hashtag> excellent <allcaps>"),
    ("NASA", "nasa <allcaps>"),
    ("NASAcool", "nasacool"),
    ("wayyyy", "way <elong>"),
    ("!!!", "! <repeat>"),
    ("holy shit!!", "holy shit ! <repeat>"),
    ("What are you doing?", "what are you doing ?"),
    ("Are you ok!?", "are you ok ! ?"),
    ("be careful what you wish for.....", "be careful what you wish for . <repeat>"),
    ("you are wayyyy out of line, buddy", "you are way <elong> out of line , buddy"),
    ("Here's an idea: be nice to them. :)", "here's an idea : be nice to them . <smile>"),
    ("Let's be sure to #getoutthevote", "let's be sure to <hashtag> getoutthevote"),
    ("We must #GetOutTheVote this November", "we must <hashtag> getoutthevote this november"),
    ("I met Samuel L. Jackson #MOTHERFUCKER", "i met samuel l . jackson <hashtag> motherfucker <allcaps>"),
    ("#", "#"),
    ("alpha#beta", "alpha#beta"),
    (".", "."),
    (":", ":"),
    (",", ","),
    ("60,", "<number> ,"),
    (",60", ", <number>"),
    ("I need .7 (aka 0.7)", "i need <number> ( aka <number> )"),
    ("7.0", "<number>"),
    ("RT @idaho: Look at me!", "<retweet> <user> : look at me !"),
    (":( ): :< >: :[ ]: D:", "<sadface> <sadface> <sadface> <sadface> <sadface> <sadface> <sadface>"),
    ("Not sad):", "not sad ) :"),
    (":L :l :| :/ :\\ :*", "<neutralface> <neutralface> <neutralface> <neutralface> <neutralface> <neutralface>"),
    ("Download to C://Users", "download to c : / / users"),
    ("I'm dying:P", "i'm dying : p"),
    (":P :p index:P :p", "<lolface> <lolface> index : p <lolface>"),
    ("I am a walrus :) wanna do this??? lets go... 3 times now YEAAAA #excellent",
     "i am a walrus <smile> wanna do this ? <repeat> lets go . <repeat> <number> times now yea <allcaps> <elong> <hashtag> excellent"),
    ("RT @somebody hey How's it going? :D", "<retweet> <user> hey how's it going ? <smile>"),
    ("", "<empty>"),
    ('I need to get some "things"', 'i need to get some " things "'),
    ("My IP is 192.168.1.1, can you help me", "my ip <allcaps> is <number> , can you help me"),
    ("Today I made 100,000 dollars", "today i made <number> dollars"),
    ("I have 1,000, what about you?", "i have <number> , what about you ?"),
    ("You need 6000, hope that helps.", "you need <number> , hope that helps ."),
    ("I am so l33t", "i am so l33t"),
    ("I will never watch RT again.", "i will never watch rt <allcaps> again ."),
])
def test_tokenize(input, expected):
    actual = tokenize(input)
    expected = expected.split()
    assert actual == expected
