#!/bin/bash
#PBS -keo
#PBS -qgpu
#PBS -l nodes=1:ppn=28,walltime=8:00:00

module load shared
module load anaconda/.anaconda

cd "$HOME/code/Sock"

python3 -W ignore::RuntimeWarning -m sock.cli.train \
    --glove "$HOME/data/glove/glove.custom.50d.xz" \
    --bots "$HOME/data/538/tweets.csv" \
    --humans "$HOME/data/cresci-2017/datasets_full.csv/genuine_accounts.csv/tweets.csv" \
    --output "$HOME/trained-50-custom-glove.pt"
