#!/bin/bash
#PBS -keo
#PBS -qgpu
#PBS -l nodes=1:ppn=28,walltime=6:00:00
#PBS -t 25,50,100,200

module load shared
module load anaconda/.anaconda

cd "$HOME/code/Sock-Puppet"

python3 -W ignore::RuntimeWarning -m sockpuppet.model.train \
    --glove "$HOME/data/glove/glove.twitter.27B.${PBS_ARRAYID}d.txt" \
    --bots "$HOME/data/538/tweets.csv" \
    --humans "$HOME/data/cresci-2017/datasets_full.csv/genuine_accounts.csv/tweets.csv" \
    --output "$HOME/trained-${PBS_ARRAYID}.pt"
